export default {
    universidad:{
        nombre:'',
        abreviacion:''
    },
    carrera:{
        nombreCarrera:'',
        nombreCoordinador:'',
        apellidoCoordinador:'',
        cantidadSemestres:8
    },
    temaCurso:{
        temaCurso:''
    },
    usuario:{
        usuario:'',
        contrasena:'',
        nombre:'',
        apellido:''
    }
}